export const FIELD_CATALOG = [
  {
    field: "patient.age",
    type: "number",
    description: "정확히 언급된 연령. 단위 year/month/day. 연령대는 age_text.",
    label: "연령",
  },
  {
    field: "patient.age_text",
    type: "string",
    description: "60대, 약 70세처럼 추정·범위·정확하지 않은 연령 원문.",
    label: "연령 표현",
  },
  {
    field: "patient.sex_reported",
    type: "string",
    description: "언급된 성별. 목소리나 이름으로 추정 금지.",
    label: "성별",
  },
  {
    field: "patient.weight",
    type: "number",
    description: "언급된 체중. 단위 미언급 시 unit=null.",
    label: "체중",
  },
  {
    field: "incident.type",
    type: "string",
    description: "질병/외상 등 명시된 발생 유형. 원인 추정 금지.",
    label: "발생 유형",
  },
  {
    field: "incident.mechanism",
    type: "string",
    description: "추락/충돌 등 명시된 사고 기전과 상황.",
    label: "사고 기전",
  },
  {
    field: "presentation.chief_complaint",
    type: "string",
    description: "이번 환자의 명시된 주호소.",
    label: "주호소",
  },
  {
    field: "presentation.symptom",
    type: "string",
    description: "동반 증상 한 항목씩. 부정/불확실성을 status로 보존.",
    label: "동반 증상",
  },
  {
    field: "presentation.location",
    type: "string",
    description: "증상/손상 위치와 좌우. group_id로 해당 증상에 연결.",
    label: "증상 위치",
  },
  {
    field: "presentation.onset",
    type: "string",
    description: "증상 시작 시점 원문. 마지막 정상 확인과 구분.",
    label: "증상 시작",
  },
  {
    field: "presentation.last_known_well",
    type: "string",
    description: "마지막으로 정상임을 확인한 시점 원문.",
    label: "마지막 정상 확인",
  },
  {
    field: "presentation.found_abnormal_at",
    type: "string",
    description: "이상 상태를 발견한 시점 원문.",
    label: "이상 발견",
  },
  {
    field: "presentation.course",
    type: "string",
    description: "증상 경과/악화/호전/소실의 명시된 내용.",
    label: "증상 경과",
  },
  {
    field: "presentation.pain_score",
    type: "number",
    description: "명시된 통증 점수만. 척도 미언급 시 unit=null.",
    label: "통증 점수",
  },
  {
    field: "exam.consciousness_text",
    type: "string",
    description: "의식 상태 관찰/호소 원문. 점수로 자동 변환 금지.",
    label: "의식 상태",
  },
  {
    field: "exam.avpu",
    type: "string",
    description: "명시적으로 평가하여 말한 AVPU 결과만.",
    label: "AVPU",
  },
  {
    field: "exam.gcs_total",
    type: "number",
    description: "명시된 GCS 총점. 자동 산출 금지.",
    label: "GCS 총점",
  },
  {
    field: "exam.gcs_eye",
    type: "number",
    description: "명시된 GCS 눈뜨기 점수.",
    label: "GCS 눈뜨기",
  },
  {
    field: "exam.gcs_verbal",
    type: "number",
    description: "명시된 GCS 언어반응 점수.",
    label: "GCS 언어",
  },
  {
    field: "exam.gcs_motor",
    type: "number",
    description: "명시된 GCS 운동반응 점수.",
    label: "GCS 운동",
  },
  {
    field: "exam.airway",
    type: "string",
    description: "명시된 기도 상태.",
    label: "기도",
  },
  {
    field: "exam.breathing",
    type: "string",
    description: "명시된 호흡 상태/자발호흡/호흡양상.",
    label: "호흡 상태",
  },
  {
    field: "exam.circulation",
    type: "string",
    description: "명시된 출혈/피부/맥박 등 관찰 내용.",
    label: "순환 상태",
  },
  {
    field: "exam.neurologic_finding",
    type: "string",
    description: "명시된 신경학적 소견. 질환 확진으로 바꾸지 않음.",
    label: "신경학적 소견",
  },
  {
    field: "exam.injury_finding",
    type: "string",
    description: "명시된 외상·손상 소견.",
    label: "손상 소견",
  },
  {
    field: "vitals.sbp",
    type: "number",
    description: "수축기 혈압. 원문이 단순 혈압 100이면 sbp로 확정 금지.",
    label: "수축기 혈압",
  },
  {
    field: "vitals.dbp",
    type: "number",
    description: "이완기 혈압. 없는 값을 채우지 않음.",
    label: "이완기 혈압",
  },
  {
    field: "vitals.pulse",
    type: "number",
    description: "맥박수.",
    label: "맥박수",
  },
  {
    field: "vitals.respiratory_rate",
    type: "number",
    description: "호흡수.",
    label: "호흡수",
  },
  {
    field: "vitals.spo2",
    type: "number",
    description: "산소포화도.",
    label: "산소포화도",
  },
  {
    field: "vitals.temperature",
    type: "number",
    description: "체온. 섭씨/화씨 구분.",
    label: "체온",
  },
  {
    field: "vitals.glucose",
    type: "number",
    description: "혈당. 단위 추정 금지.",
    label: "혈당",
  },
  {
    field: "oxygen.device",
    type: "string",
    description: "실내공기/산소공급장치 등 명시된 측정/처치 조건.",
    label: "산소 장치",
  },
  {
    field: "oxygen.flow",
    type: "number",
    description: "명시된 산소 유량.",
    label: "산소 유량",
  },
  {
    field: "history.condition",
    type: "string",
    description: "환자 자신의 관련 병력 한 항목씩. 가족 병력 제외.",
    label: "병력",
  },
  {
    field: "history.medication",
    type: "string",
    description: "복용 약제 원문. 비슷한 약명으로 교정 금지.",
    label: "복용 약제",
  },
  {
    field: "history.allergy",
    type: "string",
    description: "명시된 알레르기 항목/전반 여부. 모름과 부정 구분.",
    label: "알레르기",
  },
  {
    field: "history.anticoagulant_use",
    type: "string",
    description: "항응고제 복용에 관한 명시된 내용. 추론 금지.",
    label: "항응고제",
  },
  {
    field: "history.dialysis",
    type: "string",
    description: "명시된 투석 관련 내용.",
    label: "투석",
  },
  {
    field: "history.baseline",
    type: "string",
    description: "평소 의식/기능/측정값 등 현재와 구분한 기저 상태.",
    label: "기저 상태",
  },
  {
    field: "special.pregnancy",
    type: "string",
    description: "명시된 임신 관련 내용. 성별/나이로 판단 금지.",
    label: "임신",
  },
  {
    field: "special.gestational_age",
    type: "number",
    description: "명시된 임신 주수/일수.",
    label: "임신 주수",
  },
  {
    field: "special.exposure",
    type: "string",
    description: "명시된 약물/독성/화학물질 등의 노출.",
    label: "노출",
  },
  {
    field: "special.infection_concern",
    type: "string",
    description: "명시된 감염/격리 관련 우려. 격리 필요성 추론 금지.",
    label: "감염 관련",
  },
  {
    field: "treatment.name",
    type: "string",
    description: "시행/진행/계획/중단된 처치명. 상태와 같은 group_id 사용.",
    label: "처치명",
  },
  {
    field: "treatment.status",
    type: "string",
    description: "원문에 명시된 시행 상태. 계획을 시행 완료로 바꾸지 않음.",
    label: "처치 상태",
  },
  {
    field: "treatment.dose",
    type: "number",
    description: "명시된 처치/약물 용량.",
    label: "처치 용량",
  },
  {
    field: "treatment.route",
    type: "string",
    description: "명시된 투여 경로.",
    label: "투여 경로",
  },
  {
    field: "treatment.time",
    type: "string",
    description: "명시된 시행 시각 원문.",
    label: "처치 시각",
  },
  {
    field: "treatment.response",
    type: "string",
    description: "명시된 처치 이후 상태. 인과관계 추론 금지.",
    label: "처치 후 상태",
  },
  {
    field: "triage.pre_ktas",
    type: "number",
    description:
      "명시적으로 말한 Pre-KTAS 평가값만. KTAS나 단순 2등급을 변환하지 않음.",
    label: "Pre-KTAS",
  },
  {
    field: "assessment.stated_impression",
    type: "string",
    description: "사람이 명시한 의심/판단. 의심이면 status=uncertain.",
    label: "언급한 의심 질환",
  },
  {
    field: "assessment.requested_resource",
    type: "string",
    description: "사람이 명시적으로 요청한 자원/처치. 증상에서 생성 금지.",
    label: "요청 자원",
  },
  {
    field: "assessment.requested_department",
    type: "string",
    description: "사람이 명시적으로 요청한 진료과/전문분야.",
    label: "요청 진료과",
  },
  {
    field: "transport.preference",
    type: "string",
    description: "환자/대원이 언급한 병원 선호/이송 관련 요구. 수용 승인 아님.",
    label: "이송 선호",
  },
  {
    field: "notes.clinical_other",
    type: "string",
    description: "위 필드로 손실 없이 담기 어려운 관련 임상 원문. 식별자 제외.",
    label: "기타 임상 내용",
  },
] as const;
